### ISSUE TITLE
`HYPE`'s workflow is not ordering `Landcover` and `Soil Texture` names properly

### ISSUE THREAD

**Issue by kasra-keshavarz** [MIsmlAhmed/MAF#1]
The `HYPE` workflow is currently not ordering the `Landcover` and `Soil Texture` layers to build proper `SLC`s. 

As an example, the following land cover and soil texture layers:
```
land cover: 10 (70%), 5 (20%), and 13 (10%)
soil texture: 3 (80%) and 4 (20%)
```
should be renamed as follows:
```
land cover: 1 (70%), 2(20%), and 3(10%)
soil texture: 1 (80%) and 2 (20%)
```

Reported-by: Mohamed Ahmed <@MIsmlAhmed>

**Comment by MIsmlAhmed** [comment]
Fixed in this commit https://github.com/MIsmlAhmed/MAF/commit/b21894eb14f8a89da95445b0506eb7d975eb6432

**Comment by moghairib** [comment]
Fixed in this commit https://github.com/MIsmlAhmed/MAF/commit/b21894eb14f8a89da95445b0506eb7d975eb6432
